application: APPLICATION_NAME
version: 1
runtime: php
api_version: 1

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /
  script: index.php

- url: /index.php
  script: index.php

